# -*- coding: utf-8 -*-
"""Keccak 256.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ZZi2tL01f9o7PEdr0MIYxK9SzQH-nOY
"""

pip install eth-hash[pycryptodome]

from eth_hash.auto import keccak

keccak(b'')

preimage = keccak.new(b'part-a')
preimage.update(b'part-b')
preimage.digest()

preimage = keccak.new(b'part-a')
preimage_copy = preimage.copy()
preimage.update(b'part-b')
print(preimage.digest())
preimage_copy.update(b'part-c')
print(preimage_copy.digest())
